// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdremnuaauvyxawhjtuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcmVtbnVhYXV2eXhhd2hqdHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjIyNzIsImV4cCI6MjA3MTQzODI3Mn0.AMYJGMZ3Igh5Jfg060X5pBRfG2F_8qV0b2ayurJzJLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});